### ISSUE TITLE
[el6] php54-pgsql == php54-pgsql84

### ISSUE THREAD

**Issue by cgtx** [iuscommunity-pkg/php54-pgsql84#1]
Currently this package is available for el6.  But that version ships with postgresql 8.4, so the resulting packages basically the same.

Should we consider retiring this package from the el6 repos?  If we do, does it make sense to have `php54-pgsql` obsolete `php54-pgsql84`?

**Comment by carlwgeorge** [comment]
PHP 5.4 will be EOL on [2015-09-14](http://php.net/supported-versions.php).  This isn't worth messing with, considering the short lifespan of the package.
